import logging
from app.core.gemini_provider import GeminiProvider
from app.core.groq_provider import GroqProvider
from app.core.sarvam_provider import SarvamProvider
from app.core.huggingface_provider import HuggingFaceProvider

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class LLMRouter:
    def __init__(self):
        self.providers = {
            "gemini": GeminiProvider(),
            "groq": GroqProvider(),
            "sarvam": SarvamProvider(),
            "huggingface": HuggingFaceProvider(),
        }

        # Fallback sequence (Sarvam replaces OpenRouter)
        self.fallback_order = ["gemini", "groq", "sarvam", "huggingface"]

        # Routing rules
        self.task_routing = {
            "summary": "sarvam",
            "chat": "groq",
            "verification": "sarvam",   # Sarvam: Indian legal context
            "advisory": "sarvam"
        }

    async def generate(self, prompt: str, task: str) -> dict:
        """
        Routes the prompt to the appropriate provider based on the task.
        Implements fallback logic if the primary provider fails.
        """
        # Determine primary provider
        primary_provider_key = self.task_routing.get(task, "gemini")
        
        # Build the execution list (Primary first, then the rest in fallback order)
        execution_list = [primary_provider_key]
        for p in self.fallback_order:
            if p != primary_provider_key:
                execution_list.append(p)

        # Attempt generation with fallback logic
        for provider_key in execution_list:
            provider = self.providers.get(provider_key)
            if not provider:
                continue

            try:
                logger.info(f"Attempting generation with provider: {provider.provider_name} for task: {task}")
                
                # Execute provider logic
                result = await provider.generate(prompt)
                
                logger.info(f"LLM response generated by {provider.provider_name}")
                
                # Formatting: Handle both dict and raw string returns
                if isinstance(result, dict):
                    text = result.get("text", str(result))
                else:
                    text = str(result)

                return {
                    "text": text,
                    "provider": provider.provider_name
                }
                
            except Exception as e:
                logger.error(f"Error encountered with {provider.provider_name}: {str(e)}")
                logger.warning(f"Fallback triggered. Moving to next provider...")
                continue
        
        # If all fail
        logger.error("All providers failed to generate a response.")
        raise RuntimeError("All LLM providers failed to generate a response.")

# Instantiate router for easy import
router = LLMRouter()

async def generate(prompt: str, task: str) -> dict:
    """Convenience wrapper for the router."""
    return await router.generate(prompt, task)
